spring.application.name=ss13-ex04

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/medicine_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password

#